[env:esp32dev]
platform = espressif32
board = gemma_brd 
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=0 -std=c++14 -I${PROJECT_DIR}/src/nanopb -I${PROJECT_DIR}/src/proto
board_build.partitions = partitions_custom.csv
board_build.filesystem = littlefs
lib_extra_dirs = ~/Documents/Arduino/libraries	
lib_deps =
    sparkfun/SparkFun STUSB4500@^1.1.5
    adafruit/Adafruit BusIO@^1.16.1